### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by dmcclean**
Lots of changes to prepare for hackage:

* Explicit export list
* Clean haddocks
* Support for both 7.10 and 7.8 (@bjornbm please check 7.8 support) using CPP
* Fixed typos in cabal file
* Removed a dead file
* Updated claim of stability to provisional

### CODE REVIEW

**Comment by dmcclean** [comment]
I move to push this to hackage once you are satisfied with these changes and whichever others you may wish to make for similar reasons.

**Comment by dmcclean** [comment]
Fixes #8.

**Comment by dmcclean** [comment]
But see #10 before deciding whether to go to hackage.

**Comment by bjornbm** [comment]
Thanks! You can go ahead with hackage if you want or I can do it this evening.

**Pull request merged**
