### PR TITLE
   Type int

### LINKED ISSUE #10: Naming
Is `NumType` a good name for the main type of this package? Maybe it should be `TypeInt` or similar?

Package name seems fine, especially if we later want to tackle type rationals.

### PR DESCRIPTION
**Pull request by dmcclean**
Fixes #10.

Please test on GHC 7.8 before merging, I think there might be something I missed there since there is conditional compilation now.

### CODE REVIEW

**Comment by bjornbm** [comment]
Did you forget to push a commit? Integers has a bad import (`Natural`) and needs to change `Nat` to `TypeNat` throughout.

**Comment by dmcclean** [comment]
No, I pushed everything, those parts were just in the non-active part of 7.10s build and my search-and-replaces must have missed them.

Can you patch them up quickly? If not I will do it from a computer at work this week that still has a 7.8 install.

**Comment by dmcclean** [comment]
I _think_ that does it. I misspelled the import, and forgot to alias `TypeNat` to the name that GHC uses.

**Comment by dmcclean** [comment]
No travis's copy of 7.8 says it is still no good, but this time it's for a subtle reason. Type synonyms aren't promoted to data kind synonyms, and there's (I think) no explicit way to define one.

This solution I just pushed (is meant to) work(s) by changing the name of our homemade naturals from `TypeNat` back to `Nat` so that it is stringly interchangeable with `GHC.TypeLits.Nat` depending on which you imported.

This is inconsistent, but not worth caring about because it is not even an exposed module.

Another option would be to bring both the 7.8 and 7.10 versions over to `GHC.TypeLits`, losing `Typeable` support in 7.8 in exchange for less machinery. I have no objection to that because I'm on 7.10 and `Typeable` works there anyway.

**Comment by dmcclean** [comment]
Travis passed it. If you merge you will get both the goodness and the travis file, so you can turn on travis for the upstream repository if you want.

Once we get to hackage we can turn on travis for dimensional-dk as well.

**Comment by dmcclean** [comment]
Published this version to hackage so I could make progress.
Added you to the maintainers group, assuming your account is the one you used to publish dimensional.

Feel free to delete if there's a problem, or make 0.5.1, or whatever the appropriate response is.

**Pull request merged**
